## DataFrames III: Data Ectraction

In [2]:
import pandas as pd

## This Module's Dataset
- This module's dataset is a collection of all James Bond movies

In [3]:
bond_df = pd.read_csv("jamesbond.csv")
bond_df

,Film,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
0,Dr. No,1962,Sean Connery,Terence Young,448.8,7.0,0.6
1,From Russia with Love,1963,Sean Connery,Terence Young,543.8,12.6,1.6
2,Goldfinger,1964,Sean Connery,Guy Hamilton,820.4,18.6,3.2
3,Thunderball,1965,Sean Connery,Terence Young,848.1,41.9,4.7
4,Casino Royale,1967,David Niven,Ken Hughes,315.0,85.0,NaN
5,You Only Live Twice,1967,Sean Connery,Lewis Gilbert,514.2,59.9,4.4
6,On Her Majesty's Secret Service,1969,George Lazenby,Peter R. Hunt,291.5,37.3,0.6
7,Diamonds Are Forever,1971,Sean Connery,Guy Hamilton,442.5,34.7,5.8
8,Live and Let Die,1973,Roger Moore,Guy Hamilton,460.3,30.8,NaN
9,The Man with the Golden Gun,1974,Roger Moore,Guy Hamilton,334.0,27.7,NaN
10,The Spy Who Loved Me,1977,Roger Moore,Lewis Gilbert,533.0,45.1,NaN
11,Moonraker,1979,Roger Moore,Lewis Gilbert,535.0,91.5,NaN
12,For Your Eyes Only,1981,Roger Moore,John Glen,449.4,60.2,NaN
13,Never Say Never Again,1983,Sean Connery,Irvin Kershner,380.0,86.0,NaN
14,Octopussy,1983,Roger Moore,John Glen,373.8,53.9,7.8
15,A View to a Kill,1985,Roger Moore,John Glen,275.2,54.5,9.1
16,The Living Daylights,1987,Timothy Dalton,John Glen,313.5,68.8,5.2
17,Licence to Kill,1989,Timothy Dalton,John Glen,250.9,56.7,7.9
18,GoldenEye,1995,Pierce Brosnan,Martin Campbell,518.5,76.9,5.1
19,Tomorrow Never Dies,1997,Pierce Brosnan,Roger Spottiswoode,463.2,133.9,10.0
20,The World Is Not Enough,1999,Pierce Brosnan,Michael Apted,439.5,158.3,13.5
21,Die Another Day,2002,Pierce Brosnan,Lee Tamahori,465.4,154.2,17.9
22,Casino Royale,2006,Daniel Craig,Martin Campbell,581.5,145.3,3.3
23,Quantum of Solace,2008,Daniel Craig,Marc Forster,514.2,181.4,8.1
24,Skyfall,2012,Daniel Craig,Sam Mendes,943.5,170.2,14.5
25,Spectre,2015,Daniel Craig,Sam Mendes,726.7,206.3,30.0
26,No Time to Die,2021,Daniel Craig,Cary Joji Fukunaga,774.2,301.0,25.0

## The set_index and reset_index Methods
- The index serves as the collection of primary identifiers/labels/entrypoints for the rows.
- The fastest way to extract a row is from a sorted index by position/label
- Pandas uses index labels/values when merging different objects together.
- The `set_index` method sets an existing column as the index of the **DataFrame**
- The `reset_index` method sets the standard ascending numeric index as the index of the df
- set and reset are not mutating

In [8]:
bond = bond_df.copy()
bond.head()

,Film,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
0,Dr. No,1962,Sean Connery,Terence Young,448.8,7.0,0.6
1,From Russia with Love,1963,Sean Connery,Terence Young,543.8,12.6,1.6
2,Goldfinger,1964,Sean Connery,Guy Hamilton,820.4,18.6,3.2
3,Thunderball,1965,Sean Connery,Terence Young,848.1,41.9,4.7
4,Casino Royale,1967,David Niven,Ken Hughes,315.0,85.0,NaN

In [11]:
bond = bond.set_index("Film")

In [12]:
bond

,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
Film,,,,,,
Dr. No,1962,Sean Connery,Terence Young,448.8,7.0,0.6
From Russia with Love,1963,Sean Connery,Terence Young,543.8,12.6,1.6
Goldfinger,1964,Sean Connery,Guy Hamilton,820.4,18.6,3.2
Thunderball,1965,Sean Connery,Terence Young,848.1,41.9,4.7
Casino Royale,1967,David Niven,Ken Hughes,315.0,85.0,NaN
You Only Live Twice,1967,Sean Connery,Lewis Gilbert,514.2,59.9,4.4
On Her Majesty's Secret Service,1969,George Lazenby,Peter R. Hunt,291.5,37.3,0.6
Diamonds Are Forever,1971,Sean Connery,Guy Hamilton,442.5,34.7,5.8
Live and Let Die,1973,Roger Moore,Guy Hamilton,460.3,30.8,NaN
The Man with the Golden Gun,1974,Roger Moore,Guy Hamilton,334.0,27.7,NaN
The Spy Who Loved Me,1977,Roger Moore,Lewis Gilbert,533.0,45.1,NaN
Moonraker,1979,Roger Moore,Lewis Gilbert,535.0,91.5,NaN
For Your Eyes Only,1981,Roger Moore,John Glen,449.4,60.2,NaN
Never Say Never Again,1983,Sean Connery,Irvin Kershner,380.0,86.0,NaN
Octopussy,1983,Roger Moore,John Glen,373.8,53.9,7.8
A View to a Kill,1985,Roger Moore,John Glen,275.2,54.5,9.1
The Living Daylights,1987,Timothy Dalton,John Glen,313.5,68.8,5.2
Licence to Kill,1989,Timothy Dalton,John Glen,250.9,56.7,7.9
GoldenEye,1995,Pierce Brosnan,Martin Campbell,518.5,76.9,5.1
Tomorrow Never Dies,1997,Pierce Brosnan,Roger Spottiswoode,463.2,133.9,10.0
The World Is Not Enough,1999,Pierce Brosnan,Michael Apted,439.5,158.3,13.5
Die Another Day,2002,Pierce Brosnan,Lee Tamahori,465.4,154.2,17.9
Casino Royale,2006,Daniel Craig,Martin Campbell,581.5,145.3,3.3
Quantum of Solace,2008,Daniel Craig,Marc Forster,514.2,181.4,8.1
Skyfall,2012,Daniel Craig,Sam Mendes,943.5,170.2,14.5
Spectre,2015,Daniel Craig,Sam Mendes,726.7,206.3,30.0
No Time to Die,2021,Daniel Craig,Cary Joji Fukunaga,774.2,301.0,25.0

In [13]:
bond.reset_index()

,Film,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
0,Dr. No,1962,Sean Connery,Terence Young,448.8,7.0,0.6
1,From Russia with Love,1963,Sean Connery,Terence Young,543.8,12.6,1.6
2,Goldfinger,1964,Sean Connery,Guy Hamilton,820.4,18.6,3.2
3,Thunderball,1965,Sean Connery,Terence Young,848.1,41.9,4.7
4,Casino Royale,1967,David Niven,Ken Hughes,315.0,85.0,NaN
5,You Only Live Twice,1967,Sean Connery,Lewis Gilbert,514.2,59.9,4.4
6,On Her Majesty's Secret Service,1969,George Lazenby,Peter R. Hunt,291.5,37.3,0.6
7,Diamonds Are Forever,1971,Sean Connery,Guy Hamilton,442.5,34.7,5.8
8,Live and Let Die,1973,Roger Moore,Guy Hamilton,460.3,30.8,NaN
9,The Man with the Golden Gun,1974,Roger Moore,Guy Hamilton,334.0,27.7,NaN
10,The Spy Who Loved Me,1977,Roger Moore,Lewis Gilbert,533.0,45.1,NaN
11,Moonraker,1979,Roger Moore,Lewis Gilbert,535.0,91.5,NaN
12,For Your Eyes Only,1981,Roger Moore,John Glen,449.4,60.2,NaN
13,Never Say Never Again,1983,Sean Connery,Irvin Kershner,380.0,86.0,NaN
14,Octopussy,1983,Roger Moore,John Glen,373.8,53.9,7.8
15,A View to a Kill,1985,Roger Moore,John Glen,275.2,54.5,9.1
16,The Living Daylights,1987,Timothy Dalton,John Glen,313.5,68.8,5.2
17,Licence to Kill,1989,Timothy Dalton,John Glen,250.9,56.7,7.9
18,GoldenEye,1995,Pierce Brosnan,Martin Campbell,518.5,76.9,5.1
19,Tomorrow Never Dies,1997,Pierce Brosnan,Roger Spottiswoode,463.2,133.9,10.0
20,The World Is Not Enough,1999,Pierce Brosnan,Michael Apted,439.5,158.3,13.5
21,Die Another Day,2002,Pierce Brosnan,Lee Tamahori,465.4,154.2,17.9
22,Casino Royale,2006,Daniel Craig,Martin Campbell,581.5,145.3,3.3
23,Quantum of Solace,2008,Daniel Craig,Marc Forster,514.2,181.4,8.1
24,Skyfall,2012,Daniel Craig,Sam Mendes,943.5,170.2,14.5
25,Spectre,2015,Daniel Craig,Sam Mendes,726.7,206.3,30.0
26,No Time to Die,2021,Daniel Craig,Cary Joji Fukunaga,774.2,301.0,25.0

In [17]:
bond = bond_df.copy()
bond.set_index("Film").set_index("Year") # Setting consecutavely will kill old index... useful to reset index between sets

,Actor,Director,Box Office,Budget,Bond Actor Salary
Year,,,,,
1962,Sean Connery,Terence Young,448.8,7.0,0.6
1963,Sean Connery,Terence Young,543.8,12.6,1.6
1964,Sean Connery,Guy Hamilton,820.4,18.6,3.2
1965,Sean Connery,Terence Young,848.1,41.9,4.7
1967,David Niven,Ken Hughes,315.0,85.0,NaN
1967,Sean Connery,Lewis Gilbert,514.2,59.9,4.4
1969,George Lazenby,Peter R. Hunt,291.5,37.3,0.6
1971,Sean Connery,Guy Hamilton,442.5,34.7,5.8
1973,Roger Moore,Guy Hamilton,460.3,30.8,NaN
1974,Roger Moore,Guy Hamilton,334.0,27.7,NaN
1977,Roger Moore,Lewis Gilbert,533.0,45.1,NaN
1979,Roger Moore,Lewis Gilbert,535.0,91.5,NaN
1981,Roger Moore,John Glen,449.4,60.2,NaN
1983,Sean Connery,Irvin Kershner,380.0,86.0,NaN
1983,Roger Moore,John Glen,373.8,53.9,7.8
1985,Roger Moore,John Glen,275.2,54.5,9.1
1987,Timothy Dalton,John Glen,313.5,68.8,5.2
1989,Timothy Dalton,John Glen,250.9,56.7,7.9
1995,Pierce Brosnan,Martin Campbell,518.5,76.9,5.1
1997,Pierce Brosnan,Roger Spottiswoode,463.2,133.9,10.0
1999,Pierce Brosnan,Michael Apted,439.5,158.3,13.5
2002,Pierce Brosnan,Lee Tamahori,465.4,154.2,17.9
2006,Daniel Craig,Martin Campbell,581.5,145.3,3.3
2008,Daniel Craig,Marc Forster,514.2,181.4,8.1
2012,Daniel Craig,Sam Mendes,943.5,170.2,14.5
2015,Daniel Craig,Sam Mendes,726.7,206.3,30.0
2021,Daniel Craig,Cary Joji Fukunaga,774.2,301.0,25.0

## Retreive Rows by Index Position with iloc Accessor

In [19]:
bond = bond_df.copy()
bond.head()

,Film,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
0,Dr. No,1962,Sean Connery,Terence Young,448.8,7.0,0.6
1,From Russia with Love,1963,Sean Connery,Terence Young,543.8,12.6,1.6
2,Goldfinger,1964,Sean Connery,Guy Hamilton,820.4,18.6,3.2
3,Thunderball,1965,Sean Connery,Terence Young,848.1,41.9,4.7
4,Casino Royale,1967,David Niven,Ken Hughes,315.0,85.0,NaN

In [22]:
bond.iloc[[15,20]]

,Film,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
15,A View to a Kill,1985,Roger Moore,John Glen,275.2,54.5,9.1
20,The World Is Not Enough,1999,Pierce Brosnan,Michael Apted,439.5,158.3,13.5

## Retrieve Rows by Index Label with loc Accessor
- The loc accessor retrieves one or more rows by index label
- Provide a pair of square brackets after the accessor

In [33]:
bond = bond_df.copy().set_index("Film").sort_index() # Sort index helps speed of lookups
bond.head()

,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
Film,,,,,,
A View to a Kill,1985,Roger Moore,John Glen,275.2,54.5,9.1
Casino Royale,2006,Daniel Craig,Martin Campbell,581.5,145.3,3.3
Casino Royale,1967,David Niven,Ken Hughes,315.0,85.0,NaN
Diamonds Are Forever,1971,Sean Connery,Guy Hamilton,442.5,34.7,5.8
Die Another Day,2002,Pierce Brosnan,Lee Tamahori,465.4,154.2,17.9

In [30]:
bond.loc["Dr. No"]

Year                          1962
Actor                 Sean Connery
Director             Terence Young
Box Office                   448.8
Budget                         7.0
Bond Actor Salary              0.6
Name: Dr. No, dtype: object

In [31]:
bond.loc[["From Russia with Love", "Goldfinger"]]

,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
Film,,,,,,
From Russia with Love,1963,Sean Connery,Terence Young,543.8,12.6,1.6
Goldfinger,1964,Sean Connery,Guy Hamilton,820.4,18.6,3.2

In [35]:
bond.loc["Dimonds Are Forever": "Moonraker"] # loc accessor is inclusive of last elem unlike iloc

,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
Film,,,,,,
Dr. No,1962,Sean Connery,Terence Young,448.8,7.0,0.6
For Your Eyes Only,1981,Roger Moore,John Glen,449.4,60.2,NaN
From Russia with Love,1963,Sean Connery,Terence Young,543.8,12.6,1.6
GoldenEye,1995,Pierce Brosnan,Martin Campbell,518.5,76.9,5.1
Goldfinger,1964,Sean Connery,Guy Hamilton,820.4,18.6,3.2
Licence to Kill,1989,Timothy Dalton,John Glen,250.9,56.7,7.9
Live and Let Die,1973,Roger Moore,Guy Hamilton,460.3,30.8,NaN
Moonraker,1979,Roger Moore,Lewis Gilbert,535.0,91.5,NaN

In [36]:
bond.iloc[0:4] # this pulls 0, 1, 2, 3

,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
Film,,,,,,
A View to a Kill,1985,Roger Moore,John Glen,275.2,54.5,9.1
Casino Royale,2006,Daniel Craig,Martin Campbell,581.5,145.3,3.3
Casino Royale,1967,David Niven,Ken Hughes,315.0,85.0,NaN
Diamonds Are Forever,1971,Sean Connery,Guy Hamilton,442.5,34.7,5.8

## Second Args to loc and iloc
- The second value inside square bracks targets cols
- `iloc` requres numeric pos
- `loc` requires labels

In [41]:
bond = bond_df.copy()
bond = bond.set_index("Film").sort_index()
bond.head()

,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
Film,,,,,,
A View to a Kill,1985,Roger Moore,John Glen,275.2,54.5,9.1
Casino Royale,2006,Daniel Craig,Martin Campbell,581.5,145.3,3.3
Casino Royale,1967,David Niven,Ken Hughes,315.0,85.0,NaN
Diamonds Are Forever,1971,Sean Connery,Guy Hamilton,442.5,34.7,5.8
Die Another Day,2002,Pierce Brosnan,Lee Tamahori,465.4,154.2,17.9

In [43]:
bond.loc["Diamonds Are Forever", "Director"]

'Guy Hamilton'

In [44]:
bond.iloc[0, 1]

'Roger Moore'

In [45]:
bond.loc[["Octopussy", "GoldenEye"], "Director"]

Film
Octopussy          John Glen
GoldenEye    Martin Campbell
Name: Director, dtype: object

In [46]:
bond.loc[["Octopussy", "GoldenEye"], "Director": "Budget"]

                  Director  Box Office  Budget
Film
Octopussy        John Glen       373.8    53.9
GoldenEye  Martin Campbell       518.5    76.9

In [47]:
bond.loc["GoldenEye":"Octopussy", "Director":"Budget"]

                                 Director  Box Office  Budget
Film
GoldenEye                 Martin Campbell       518.5    76.9
Goldfinger                   Guy Hamilton       820.4    18.6
Licence to Kill                 John Glen       250.9    56.7
Live and Let Die             Guy Hamilton       460.3    30.8
Moonraker                   Lewis Gilbert       535.0    91.5
Never Say Never Again      Irvin Kershner       380.0    86.0
No Time to Die         Cary Joji Fukunaga       774.2   301.0
Octopussy                       John Glen       373.8    53.9

In [48]:
bond.loc["GoldenEye":"Octopussy", ["Actor", "Bond Actor Salary", "Year"]]

                                Actor  Bond Actor Salary  Year
Film
GoldenEye              Pierce Brosnan                5.1  1995
Goldfinger               Sean Connery                3.2  1964
Licence to Kill        Timothy Dalton                7.9  1989
Live and Let Die          Roger Moore                NaN  1973
Moonraker                 Roger Moore                NaN  1979
Never Say Never Again    Sean Connery                NaN  1983
No Time to Die           Daniel Craig               25.0  2021
Octopussy                 Roger Moore                7.8  1983

In [49]:
## Overwrite a Value in a DatFrame

In [55]:
bond = bond_df.copy().set_index("Film").sort_index()
bond.head()

,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
Film,,,,,,
A View to a Kill,1985,Roger Moore,John Glen,275.2,54.5,9.1
Casino Royale,2006,Daniel Craig,Martin Campbell,581.5,145.3,3.3
Casino Royale,1967,David Niven,Ken Hughes,315.0,85.0,NaN
Diamonds Are Forever,1971,Sean Connery,Guy Hamilton,442.5,34.7,5.8
Die Another Day,2002,Pierce Brosnan,Lee Tamahori,465.4,154.2,17.9

In [56]:
bond.loc["A View to a Kill", "Year"] = 1882

In [57]:
bond.head()

,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
Film,,,,,,
A View to a Kill,1882,Roger Moore,John Glen,275.2,54.5,9.1
Casino Royale,2006,Daniel Craig,Martin Campbell,581.5,145.3,3.3
Casino Royale,1967,David Niven,Ken Hughes,315.0,85.0,NaN
Diamonds Are Forever,1971,Sean Connery,Guy Hamilton,442.5,34.7,5.8
Die Another Day,2002,Pierce Brosnan,Lee Tamahori,465.4,154.2,17.9

## Overwrite Multiple Values in a Data Frame
- The replace method replaces all occurences of a **Series** value with another value (think of it like "Find and Replace").
- To overwrite multiple values on a **DF** remember to use an accessor on the df
- `loc` and `iloc` can accept a boolean series. Use them to target the values to overwrite

In [58]:
bond = bond_df.copy().set_index("Film").sort_index()
bond.head()

,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
Film,,,,,,
A View to a Kill,1985,Roger Moore,John Glen,275.2,54.5,9.1
Casino Royale,2006,Daniel Craig,Martin Campbell,581.5,145.3,3.3
Casino Royale,1967,David Niven,Ken Hughes,315.0,85.0,NaN
Diamonds Are Forever,1971,Sean Connery,Guy Hamilton,442.5,34.7,5.8
Die Another Day,2002,Pierce Brosnan,Lee Tamahori,465.4,154.2,17.9

In [60]:
bond["Actor"] = bond["Actor"].replace("Sean Connery", "Sir Sean Connery")

In [61]:
bond

,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
Film,,,,,,
A View to a Kill,1985,Roger Moore,John Glen,275.2,54.5,9.1
Casino Royale,2006,Daniel Craig,Martin Campbell,581.5,145.3,3.3
Casino Royale,1967,David Niven,Ken Hughes,315.0,85.0,NaN
Diamonds Are Forever,1971,Sir Sean Connery,Guy Hamilton,442.5,34.7,5.8
Die Another Day,2002,Pierce Brosnan,Lee Tamahori,465.4,154.2,17.9
Dr. No,1962,Sir Sean Connery,Terence Young,448.8,7.0,0.6
For Your Eyes Only,1981,Roger Moore,John Glen,449.4,60.2,NaN
From Russia with Love,1963,Sir Sean Connery,Terence Young,543.8,12.6,1.6
GoldenEye,1995,Pierce Brosnan,Martin Campbell,518.5,76.9,5.1
Goldfinger,1964,Sir Sean Connery,Guy Hamilton,820.4,18.6,3.2
Licence to Kill,1989,Timothy Dalton,John Glen,250.9,56.7,7.9
Live and Let Die,1973,Roger Moore,Guy Hamilton,460.3,30.8,NaN
Moonraker,1979,Roger Moore,Lewis Gilbert,535.0,91.5,NaN
Never Say Never Again,1983,Sir Sean Connery,Irvin Kershner,380.0,86.0,NaN
No Time to Die,2021,Daniel Craig,Cary Joji Fukunaga,774.2,301.0,25.0
Octopussy,1983,Roger Moore,John Glen,373.8,53.9,7.8
On Her Majesty's Secret Service,1969,George Lazenby,Peter R. Hunt,291.5,37.3,0.6
Quantum of Solace,2008,Daniel Craig,Marc Forster,514.2,181.4,8.1
Skyfall,2012,Daniel Craig,Sam Mendes,943.5,170.2,14.5
Spectre,2015,Daniel Craig,Sam Mendes,726.7,206.3,30.0
The Living Daylights,1987,Timothy Dalton,John Glen,313.5,68.8,5.2
The Man with the Golden Gun,1974,Roger Moore,Guy Hamilton,334.0,27.7,NaN
The Spy Who Loved Me,1977,Roger Moore,Lewis Gilbert,533.0,45.1,NaN
The World Is Not Enough,1999,Pierce Brosnan,Michael Apted,439.5,158.3,13.5
Thunderball,1965,Sir Sean Connery,Terence Young,848.1,41.9,4.7
Tomorrow Never Dies,1997,Pierce Brosnan,Roger Spottiswoode,463.2,133.9,10.0
You Only Live Twice,1967,Sir Sean Connery,Lewis Gilbert,514.2,59.9,4.4

In [62]:
bond = bond_df.copy().set_index("Film").sort_index()
bond.head()

,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
Film,,,,,,
A View to a Kill,1985,Roger Moore,John Glen,275.2,54.5,9.1
Casino Royale,2006,Daniel Craig,Martin Campbell,581.5,145.3,3.3
Casino Royale,1967,David Niven,Ken Hughes,315.0,85.0,NaN
Diamonds Are Forever,1971,Sean Connery,Guy Hamilton,442.5,34.7,5.8
Die Another Day,2002,Pierce Brosnan,Lee Tamahori,465.4,154.2,17.9

In [66]:
bond[bond["Actor"] == "Sean Connery"].loc[:, "Actor"] = "Sir Sean Connery"

/tmp/ipykernel_1460472/44046152.py:1: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  bond[bond["Actor"] == "Sean Connery"].loc[:, "Actor"] = "Sir Sean Connery"

In [70]:
bond.loc[bond["Actor"] == "Sean Connery", "Actor"] = "Sir Sean Connery"

In [71]:
bond

,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
Film,,,,,,
A View to a Kill,1985,Roger Moore,John Glen,275.2,54.5,9.1
Casino Royale,2006,Daniel Craig,Martin Campbell,581.5,145.3,3.3
Casino Royale,1967,David Niven,Ken Hughes,315.0,85.0,NaN
Diamonds Are Forever,1971,Sir Sean Connery,Guy Hamilton,442.5,34.7,5.8
Die Another Day,2002,Pierce Brosnan,Lee Tamahori,465.4,154.2,17.9
Dr. No,1962,Sir Sean Connery,Terence Young,448.8,7.0,0.6
For Your Eyes Only,1981,Roger Moore,John Glen,449.4,60.2,NaN
From Russia with Love,1963,Sir Sean Connery,Terence Young,543.8,12.6,1.6
GoldenEye,1995,Pierce Brosnan,Martin Campbell,518.5,76.9,5.1
Goldfinger,1964,Sir Sean Connery,Guy Hamilton,820.4,18.6,3.2
Licence to Kill,1989,Timothy Dalton,John Glen,250.9,56.7,7.9
Live and Let Die,1973,Roger Moore,Guy Hamilton,460.3,30.8,NaN
Moonraker,1979,Roger Moore,Lewis Gilbert,535.0,91.5,NaN
Never Say Never Again,1983,Sir Sean Connery,Irvin Kershner,380.0,86.0,NaN
No Time to Die,2021,Daniel Craig,Cary Joji Fukunaga,774.2,301.0,25.0
Octopussy,1983,Roger Moore,John Glen,373.8,53.9,7.8
On Her Majesty's Secret Service,1969,George Lazenby,Peter R. Hunt,291.5,37.3,0.6
Quantum of Solace,2008,Daniel Craig,Marc Forster,514.2,181.4,8.1
Skyfall,2012,Daniel Craig,Sam Mendes,943.5,170.2,14.5
Spectre,2015,Daniel Craig,Sam Mendes,726.7,206.3,30.0
The Living Daylights,1987,Timothy Dalton,John Glen,313.5,68.8,5.2
The Man with the Golden Gun,1974,Roger Moore,Guy Hamilton,334.0,27.7,NaN
The Spy Who Loved Me,1977,Roger Moore,Lewis Gilbert,533.0,45.1,NaN
The World Is Not Enough,1999,Pierce Brosnan,Michael Apted,439.5,158.3,13.5
Thunderball,1965,Sir Sean Connery,Terence Young,848.1,41.9,4.7
Tomorrow Never Dies,1997,Pierce Brosnan,Roger Spottiswoode,463.2,133.9,10.0
You Only Live Twice,1967,Sir Sean Connery,Lewis Gilbert,514.2,59.9,4.4

## Rename Index Labels or Columns in a DataFrame

In [72]:
bond = bond_df.copy().set_index("Film").sort_index()
bond.head()

,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
Film,,,,,,
A View to a Kill,1985,Roger Moore,John Glen,275.2,54.5,9.1
Casino Royale,2006,Daniel Craig,Martin Campbell,581.5,145.3,3.3
Casino Royale,1967,David Niven,Ken Hughes,315.0,85.0,NaN
Diamonds Are Forever,1971,Sean Connery,Guy Hamilton,442.5,34.7,5.8
Die Another Day,2002,Pierce Brosnan,Lee Tamahori,465.4,154.2,17.9

In [75]:
bond.rename(columns={"Bond Actor Salary": "Salary", "Box Office": "Revenue"})

,Year,Actor,Director,Revenue,Budget,Salary
Film,,,,,,
A View to a Kill,1985,Roger Moore,John Glen,275.2,54.5,9.1
Casino Royale,2006,Daniel Craig,Martin Campbell,581.5,145.3,3.3
Casino Royale,1967,David Niven,Ken Hughes,315.0,85.0,NaN
Diamonds Are Forever,1971,Sean Connery,Guy Hamilton,442.5,34.7,5.8
Die Another Day,2002,Pierce Brosnan,Lee Tamahori,465.4,154.2,17.9
Dr. No,1962,Sean Connery,Terence Young,448.8,7.0,0.6
For Your Eyes Only,1981,Roger Moore,John Glen,449.4,60.2,NaN
From Russia with Love,1963,Sean Connery,Terence Young,543.8,12.6,1.6
GoldenEye,1995,Pierce Brosnan,Martin Campbell,518.5,76.9,5.1
Goldfinger,1964,Sean Connery,Guy Hamilton,820.4,18.6,3.2
Licence to Kill,1989,Timothy Dalton,John Glen,250.9,56.7,7.9
Live and Let Die,1973,Roger Moore,Guy Hamilton,460.3,30.8,NaN
Moonraker,1979,Roger Moore,Lewis Gilbert,535.0,91.5,NaN
Never Say Never Again,1983,Sean Connery,Irvin Kershner,380.0,86.0,NaN
No Time to Die,2021,Daniel Craig,Cary Joji Fukunaga,774.2,301.0,25.0
Octopussy,1983,Roger Moore,John Glen,373.8,53.9,7.8
On Her Majesty's Secret Service,1969,George Lazenby,Peter R. Hunt,291.5,37.3,0.6
Quantum of Solace,2008,Daniel Craig,Marc Forster,514.2,181.4,8.1
Skyfall,2012,Daniel Craig,Sam Mendes,943.5,170.2,14.5
Spectre,2015,Daniel Craig,Sam Mendes,726.7,206.3,30.0
The Living Daylights,1987,Timothy Dalton,John Glen,313.5,68.8,5.2
The Man with the Golden Gun,1974,Roger Moore,Guy Hamilton,334.0,27.7,NaN
The Spy Who Loved Me,1977,Roger Moore,Lewis Gilbert,533.0,45.1,NaN
The World Is Not Enough,1999,Pierce Brosnan,Michael Apted,439.5,158.3,13.5
Thunderball,1965,Sean Connery,Terence Young,848.1,41.9,4.7
Tomorrow Never Dies,1997,Pierce Brosnan,Roger Spottiswoode,463.2,133.9,10.0
You Only Live Twice,1967,Sean Connery,Lewis Gilbert,514.2,59.9,4.4

In [76]:
bond.rename(index={"Dr. No": "Dr No", "GoldenEye": "Golden Eye"})

,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
Film,,,,,,
A View to a Kill,1985,Roger Moore,John Glen,275.2,54.5,9.1
Casino Royale,2006,Daniel Craig,Martin Campbell,581.5,145.3,3.3
Casino Royale,1967,David Niven,Ken Hughes,315.0,85.0,NaN
Diamonds Are Forever,1971,Sean Connery,Guy Hamilton,442.5,34.7,5.8
Die Another Day,2002,Pierce Brosnan,Lee Tamahori,465.4,154.2,17.9
Dr No,1962,Sean Connery,Terence Young,448.8,7.0,0.6
For Your Eyes Only,1981,Roger Moore,John Glen,449.4,60.2,NaN
From Russia with Love,1963,Sean Connery,Terence Young,543.8,12.6,1.6
Golden Eye,1995,Pierce Brosnan,Martin Campbell,518.5,76.9,5.1
Goldfinger,1964,Sean Connery,Guy Hamilton,820.4,18.6,3.2
Licence to Kill,1989,Timothy Dalton,John Glen,250.9,56.7,7.9
Live and Let Die,1973,Roger Moore,Guy Hamilton,460.3,30.8,NaN
Moonraker,1979,Roger Moore,Lewis Gilbert,535.0,91.5,NaN
Never Say Never Again,1983,Sean Connery,Irvin Kershner,380.0,86.0,NaN
No Time to Die,2021,Daniel Craig,Cary Joji Fukunaga,774.2,301.0,25.0
Octopussy,1983,Roger Moore,John Glen,373.8,53.9,7.8
On Her Majesty's Secret Service,1969,George Lazenby,Peter R. Hunt,291.5,37.3,0.6
Quantum of Solace,2008,Daniel Craig,Marc Forster,514.2,181.4,8.1
Skyfall,2012,Daniel Craig,Sam Mendes,943.5,170.2,14.5
Spectre,2015,Daniel Craig,Sam Mendes,726.7,206.3,30.0
The Living Daylights,1987,Timothy Dalton,John Glen,313.5,68.8,5.2
The Man with the Golden Gun,1974,Roger Moore,Guy Hamilton,334.0,27.7,NaN
The Spy Who Loved Me,1977,Roger Moore,Lewis Gilbert,533.0,45.1,NaN
The World Is Not Enough,1999,Pierce Brosnan,Michael Apted,439.5,158.3,13.5
Thunderball,1965,Sean Connery,Terence Young,848.1,41.9,4.7
Tomorrow Never Dies,1997,Pierce Brosnan,Roger Spottiswoode,463.2,133.9,10.0
You Only Live Twice,1967,Sean Connery,Lewis Gilbert,514.2,59.9,4.4

In [78]:
bond.columns = ["Year", "Bond Guy", "Camera Dude", "Revenues", "Cost", "Salary"] # can be assigned to with an array of same number of elems

In [79]:
bond

,Year,Bond Guy,Camera Dude,Revenues,Cost,Salary
Film,,,,,,
A View to a Kill,1985,Roger Moore,John Glen,275.2,54.5,9.1
Casino Royale,2006,Daniel Craig,Martin Campbell,581.5,145.3,3.3
Casino Royale,1967,David Niven,Ken Hughes,315.0,85.0,NaN
Diamonds Are Forever,1971,Sean Connery,Guy Hamilton,442.5,34.7,5.8
Die Another Day,2002,Pierce Brosnan,Lee Tamahori,465.4,154.2,17.9
Dr. No,1962,Sean Connery,Terence Young,448.8,7.0,0.6
For Your Eyes Only,1981,Roger Moore,John Glen,449.4,60.2,NaN
From Russia with Love,1963,Sean Connery,Terence Young,543.8,12.6,1.6
GoldenEye,1995,Pierce Brosnan,Martin Campbell,518.5,76.9,5.1
Goldfinger,1964,Sean Connery,Guy Hamilton,820.4,18.6,3.2
Licence to Kill,1989,Timothy Dalton,John Glen,250.9,56.7,7.9
Live and Let Die,1973,Roger Moore,Guy Hamilton,460.3,30.8,NaN
Moonraker,1979,Roger Moore,Lewis Gilbert,535.0,91.5,NaN
Never Say Never Again,1983,Sean Connery,Irvin Kershner,380.0,86.0,NaN
No Time to Die,2021,Daniel Craig,Cary Joji Fukunaga,774.2,301.0,25.0
Octopussy,1983,Roger Moore,John Glen,373.8,53.9,7.8
On Her Majesty's Secret Service,1969,George Lazenby,Peter R. Hunt,291.5,37.3,0.6
Quantum of Solace,2008,Daniel Craig,Marc Forster,514.2,181.4,8.1
Skyfall,2012,Daniel Craig,Sam Mendes,943.5,170.2,14.5
Spectre,2015,Daniel Craig,Sam Mendes,726.7,206.3,30.0
The Living Daylights,1987,Timothy Dalton,John Glen,313.5,68.8,5.2
The Man with the Golden Gun,1974,Roger Moore,Guy Hamilton,334.0,27.7,NaN
The Spy Who Loved Me,1977,Roger Moore,Lewis Gilbert,533.0,45.1,NaN
The World Is Not Enough,1999,Pierce Brosnan,Michael Apted,439.5,158.3,13.5
Thunderball,1965,Sean Connery,Terence Young,848.1,41.9,4.7
Tomorrow Never Dies,1997,Pierce Brosnan,Roger Spottiswoode,463.2,133.9,10.0
You Only Live Twice,1967,Sean Connery,Lewis Gilbert,514.2,59.9,4.4

bond.columns[3] = "The Money" # Can't assign to position in index

## Delete Rows or Columns from a Dataframe
- `drop` method will delete rows/columns from the df non-mutating
- pass `index` or `columns` param with column names to remove
- The `pop` column removes and returns a single **Series** mutating df
- Python `del` method also removes a column

In [4]:
bond = bond_df.copy().set_index("Film").sort_index()
bond.head()

,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
Film,,,,,,
A View to a Kill,1985,Roger Moore,John Glen,275.2,54.5,9.1
Casino Royale,2006,Daniel Craig,Martin Campbell,581.5,145.3,3.3
Casino Royale,1967,David Niven,Ken Hughes,315.0,85.0,NaN
Diamonds Are Forever,1971,Sean Connery,Guy Hamilton,442.5,34.7,5.8
Die Another Day,2002,Pierce Brosnan,Lee Tamahori,465.4,154.2,17.9

In [5]:
bond.drop(columns=["Box Office", "Budget"])

,Year,Actor,Director,Bond Actor Salary
Film,,,,
A View to a Kill,1985,Roger Moore,John Glen,9.1
Casino Royale,2006,Daniel Craig,Martin Campbell,3.3
Casino Royale,1967,David Niven,Ken Hughes,NaN
Diamonds Are Forever,1971,Sean Connery,Guy Hamilton,5.8
Die Another Day,2002,Pierce Brosnan,Lee Tamahori,17.9
Dr. No,1962,Sean Connery,Terence Young,0.6
For Your Eyes Only,1981,Roger Moore,John Glen,NaN
From Russia with Love,1963,Sean Connery,Terence Young,1.6
GoldenEye,1995,Pierce Brosnan,Martin Campbell,5.1
Goldfinger,1964,Sean Connery,Guy Hamilton,3.2
Licence to Kill,1989,Timothy Dalton,John Glen,7.9
Live and Let Die,1973,Roger Moore,Guy Hamilton,NaN
Moonraker,1979,Roger Moore,Lewis Gilbert,NaN
Never Say Never Again,1983,Sean Connery,Irvin Kershner,NaN
No Time to Die,2021,Daniel Craig,Cary Joji Fukunaga,25.0
Octopussy,1983,Roger Moore,John Glen,7.8
On Her Majesty's Secret Service,1969,George Lazenby,Peter R. Hunt,0.6
Quantum of Solace,2008,Daniel Craig,Marc Forster,8.1
Skyfall,2012,Daniel Craig,Sam Mendes,14.5
Spectre,2015,Daniel Craig,Sam Mendes,30.0
The Living Daylights,1987,Timothy Dalton,John Glen,5.2
The Man with the Golden Gun,1974,Roger Moore,Guy Hamilton,NaN
The Spy Who Loved Me,1977,Roger Moore,Lewis Gilbert,NaN
The World Is Not Enough,1999,Pierce Brosnan,Michael Apted,13.5
Thunderball,1965,Sean Connery,Terence Young,4.7
Tomorrow Never Dies,1997,Pierce Brosnan,Roger Spottiswoode,10.0
You Only Live Twice,1967,Sean Connery,Lewis Gilbert,4.4

In [6]:
bond

,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
Film,,,,,,
A View to a Kill,1985,Roger Moore,John Glen,275.2,54.5,9.1
Casino Royale,2006,Daniel Craig,Martin Campbell,581.5,145.3,3.3
Casino Royale,1967,David Niven,Ken Hughes,315.0,85.0,NaN
Diamonds Are Forever,1971,Sean Connery,Guy Hamilton,442.5,34.7,5.8
Die Another Day,2002,Pierce Brosnan,Lee Tamahori,465.4,154.2,17.9
Dr. No,1962,Sean Connery,Terence Young,448.8,7.0,0.6
For Your Eyes Only,1981,Roger Moore,John Glen,449.4,60.2,NaN
From Russia with Love,1963,Sean Connery,Terence Young,543.8,12.6,1.6
GoldenEye,1995,Pierce Brosnan,Martin Campbell,518.5,76.9,5.1
Goldfinger,1964,Sean Connery,Guy Hamilton,820.4,18.6,3.2
Licence to Kill,1989,Timothy Dalton,John Glen,250.9,56.7,7.9
Live and Let Die,1973,Roger Moore,Guy Hamilton,460.3,30.8,NaN
Moonraker,1979,Roger Moore,Lewis Gilbert,535.0,91.5,NaN
Never Say Never Again,1983,Sean Connery,Irvin Kershner,380.0,86.0,NaN
No Time to Die,2021,Daniel Craig,Cary Joji Fukunaga,774.2,301.0,25.0
Octopussy,1983,Roger Moore,John Glen,373.8,53.9,7.8
On Her Majesty's Secret Service,1969,George Lazenby,Peter R. Hunt,291.5,37.3,0.6
Quantum of Solace,2008,Daniel Craig,Marc Forster,514.2,181.4,8.1
Skyfall,2012,Daniel Craig,Sam Mendes,943.5,170.2,14.5
Spectre,2015,Daniel Craig,Sam Mendes,726.7,206.3,30.0
The Living Daylights,1987,Timothy Dalton,John Glen,313.5,68.8,5.2
The Man with the Golden Gun,1974,Roger Moore,Guy Hamilton,334.0,27.7,NaN
The Spy Who Loved Me,1977,Roger Moore,Lewis Gilbert,533.0,45.1,NaN
The World Is Not Enough,1999,Pierce Brosnan,Michael Apted,439.5,158.3,13.5
Thunderball,1965,Sean Connery,Terence Young,848.1,41.9,4.7
Tomorrow Never Dies,1997,Pierce Brosnan,Roger Spottiswoode,463.2,133.9,10.0
You Only Live Twice,1967,Sean Connery,Lewis Gilbert,514.2,59.9,4.4

In [7]:
bond.drop(index=["No Time to Die"]) # If this index occurs +1 times then will drop all of those

,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
Film,,,,,,
A View to a Kill,1985,Roger Moore,John Glen,275.2,54.5,9.1
Casino Royale,2006,Daniel Craig,Martin Campbell,581.5,145.3,3.3
Casino Royale,1967,David Niven,Ken Hughes,315.0,85.0,NaN
Diamonds Are Forever,1971,Sean Connery,Guy Hamilton,442.5,34.7,5.8
Die Another Day,2002,Pierce Brosnan,Lee Tamahori,465.4,154.2,17.9
Dr. No,1962,Sean Connery,Terence Young,448.8,7.0,0.6
For Your Eyes Only,1981,Roger Moore,John Glen,449.4,60.2,NaN
From Russia with Love,1963,Sean Connery,Terence Young,543.8,12.6,1.6
GoldenEye,1995,Pierce Brosnan,Martin Campbell,518.5,76.9,5.1
Goldfinger,1964,Sean Connery,Guy Hamilton,820.4,18.6,3.2
Licence to Kill,1989,Timothy Dalton,John Glen,250.9,56.7,7.9
Live and Let Die,1973,Roger Moore,Guy Hamilton,460.3,30.8,NaN
Moonraker,1979,Roger Moore,Lewis Gilbert,535.0,91.5,NaN
Never Say Never Again,1983,Sean Connery,Irvin Kershner,380.0,86.0,NaN
Octopussy,1983,Roger Moore,John Glen,373.8,53.9,7.8
On Her Majesty's Secret Service,1969,George Lazenby,Peter R. Hunt,291.5,37.3,0.6
Quantum of Solace,2008,Daniel Craig,Marc Forster,514.2,181.4,8.1
Skyfall,2012,Daniel Craig,Sam Mendes,943.5,170.2,14.5
Spectre,2015,Daniel Craig,Sam Mendes,726.7,206.3,30.0
The Living Daylights,1987,Timothy Dalton,John Glen,313.5,68.8,5.2
The Man with the Golden Gun,1974,Roger Moore,Guy Hamilton,334.0,27.7,NaN
The Spy Who Loved Me,1977,Roger Moore,Lewis Gilbert,533.0,45.1,NaN
The World Is Not Enough,1999,Pierce Brosnan,Michael Apted,439.5,158.3,13.5
Thunderball,1965,Sean Connery,Terence Young,848.1,41.9,4.7
Tomorrow Never Dies,1997,Pierce Brosnan,Roger Spottiswoode,463.2,133.9,10.0
You Only Live Twice,1967,Sean Connery,Lewis Gilbert,514.2,59.9,4.4

In [8]:
bond.drop(index=["No Time to Die", "Casino Royale"], columns=["Box Office", "Budget"])

,Year,Actor,Director,Bond Actor Salary
Film,,,,
A View to a Kill,1985,Roger Moore,John Glen,9.1
Diamonds Are Forever,1971,Sean Connery,Guy Hamilton,5.8
Die Another Day,2002,Pierce Brosnan,Lee Tamahori,17.9
Dr. No,1962,Sean Connery,Terence Young,0.6
For Your Eyes Only,1981,Roger Moore,John Glen,NaN
From Russia with Love,1963,Sean Connery,Terence Young,1.6
GoldenEye,1995,Pierce Brosnan,Martin Campbell,5.1
Goldfinger,1964,Sean Connery,Guy Hamilton,3.2
Licence to Kill,1989,Timothy Dalton,John Glen,7.9
Live and Let Die,1973,Roger Moore,Guy Hamilton,NaN
Moonraker,1979,Roger Moore,Lewis Gilbert,NaN
Never Say Never Again,1983,Sean Connery,Irvin Kershner,NaN
Octopussy,1983,Roger Moore,John Glen,7.8
On Her Majesty's Secret Service,1969,George Lazenby,Peter R. Hunt,0.6
Quantum of Solace,2008,Daniel Craig,Marc Forster,8.1
Skyfall,2012,Daniel Craig,Sam Mendes,14.5
Spectre,2015,Daniel Craig,Sam Mendes,30.0
The Living Daylights,1987,Timothy Dalton,John Glen,5.2
The Man with the Golden Gun,1974,Roger Moore,Guy Hamilton,NaN
The Spy Who Loved Me,1977,Roger Moore,Lewis Gilbert,NaN
The World Is Not Enough,1999,Pierce Brosnan,Michael Apted,13.5
Thunderball,1965,Sean Connery,Terence Young,4.7
Tomorrow Never Dies,1997,Pierce Brosnan,Roger Spottiswoode,10.0
You Only Live Twice,1967,Sean Connery,Lewis Gilbert,4.4

In [9]:
bond.pop("Actor")

Film
A View to a Kill                      Roger Moore
Casino Royale                        Daniel Craig
Casino Royale                         David Niven
Diamonds Are Forever                 Sean Connery
Die Another Day                    Pierce Brosnan
Dr. No                               Sean Connery
For Your Eyes Only                    Roger Moore
From Russia with Love                Sean Connery
GoldenEye                          Pierce Brosnan
Goldfinger                           Sean Connery
Licence to Kill                    Timothy Dalton
Live and Let Die                      Roger Moore
Moonraker                             Roger Moore
Never Say Never Again                Sean Connery
No Time to Die                       Daniel Craig
Octopussy                             Roger Moore
On Her Majesty's Secret Service    George Lazenby
Quantum of Solace                    Daniel Craig
Skyfall                              Daniel Craig
Spectre                              Daniel Craig
The Living Daylights               Timothy Dalton
The Man with the Golden Gun           Roger Moore
The Spy Who Loved Me                  Roger Moore
The World Is Not Enough            Pierce Brosnan
Thunderball                          Sean Connery
Tomorrow Never Dies                Pierce Brosnan
You Only Live Twice                  Sean Connery
Name: Actor, dtype: object

In [10]:
bond

,Year,Director,Box Office,Budget,Bond Actor Salary
Film,,,,,
A View to a Kill,1985,John Glen,275.2,54.5,9.1
Casino Royale,2006,Martin Campbell,581.5,145.3,3.3
Casino Royale,1967,Ken Hughes,315.0,85.0,NaN
Diamonds Are Forever,1971,Guy Hamilton,442.5,34.7,5.8
Die Another Day,2002,Lee Tamahori,465.4,154.2,17.9
Dr. No,1962,Terence Young,448.8,7.0,0.6
For Your Eyes Only,1981,John Glen,449.4,60.2,NaN
From Russia with Love,1963,Terence Young,543.8,12.6,1.6
GoldenEye,1995,Martin Campbell,518.5,76.9,5.1
Goldfinger,1964,Guy Hamilton,820.4,18.6,3.2
Licence to Kill,1989,John Glen,250.9,56.7,7.9
Live and Let Die,1973,Guy Hamilton,460.3,30.8,NaN
Moonraker,1979,Lewis Gilbert,535.0,91.5,NaN
Never Say Never Again,1983,Irvin Kershner,380.0,86.0,NaN
No Time to Die,2021,Cary Joji Fukunaga,774.2,301.0,25.0
Octopussy,1983,John Glen,373.8,53.9,7.8
On Her Majesty's Secret Service,1969,Peter R. Hunt,291.5,37.3,0.6
Quantum of Solace,2008,Marc Forster,514.2,181.4,8.1
Skyfall,2012,Sam Mendes,943.5,170.2,14.5
Spectre,2015,Sam Mendes,726.7,206.3,30.0
The Living Daylights,1987,John Glen,313.5,68.8,5.2
The Man with the Golden Gun,1974,Guy Hamilton,334.0,27.7,NaN
The Spy Who Loved Me,1977,Lewis Gilbert,533.0,45.1,NaN
The World Is Not Enough,1999,Michael Apted,439.5,158.3,13.5
Thunderball,1965,Terence Young,848.1,41.9,4.7
Tomorrow Never Dies,1997,Roger Spottiswoode,463.2,133.9,10.0
You Only Live Twice,1967,Lewis Gilbert,514.2,59.9,4.4

In [11]:
bond = bond_df.copy().set_index("Film").sort_index()
bond.head()

,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
Film,,,,,,
A View to a Kill,1985,Roger Moore,John Glen,275.2,54.5,9.1
Casino Royale,2006,Daniel Craig,Martin Campbell,581.5,145.3,3.3
Casino Royale,1967,David Niven,Ken Hughes,315.0,85.0,NaN
Diamonds Are Forever,1971,Sean Connery,Guy Hamilton,442.5,34.7,5.8
Die Another Day,2002,Pierce Brosnan,Lee Tamahori,465.4,154.2,17.9

In [12]:
del bond["Year"]

In [13]:
bond

,Actor,Director,Box Office,Budget,Bond Actor Salary
Film,,,,,
A View to a Kill,Roger Moore,John Glen,275.2,54.5,9.1
Casino Royale,Daniel Craig,Martin Campbell,581.5,145.3,3.3
Casino Royale,David Niven,Ken Hughes,315.0,85.0,NaN
Diamonds Are Forever,Sean Connery,Guy Hamilton,442.5,34.7,5.8
Die Another Day,Pierce Brosnan,Lee Tamahori,465.4,154.2,17.9
Dr. No,Sean Connery,Terence Young,448.8,7.0,0.6
For Your Eyes Only,Roger Moore,John Glen,449.4,60.2,NaN
From Russia with Love,Sean Connery,Terence Young,543.8,12.6,1.6
GoldenEye,Pierce Brosnan,Martin Campbell,518.5,76.9,5.1
Goldfinger,Sean Connery,Guy Hamilton,820.4,18.6,3.2
Licence to Kill,Timothy Dalton,John Glen,250.9,56.7,7.9
Live and Let Die,Roger Moore,Guy Hamilton,460.3,30.8,NaN
Moonraker,Roger Moore,Lewis Gilbert,535.0,91.5,NaN
Never Say Never Again,Sean Connery,Irvin Kershner,380.0,86.0,NaN
No Time to Die,Daniel Craig,Cary Joji Fukunaga,774.2,301.0,25.0
Octopussy,Roger Moore,John Glen,373.8,53.9,7.8
On Her Majesty's Secret Service,George Lazenby,Peter R. Hunt,291.5,37.3,0.6
Quantum of Solace,Daniel Craig,Marc Forster,514.2,181.4,8.1
Skyfall,Daniel Craig,Sam Mendes,943.5,170.2,14.5
Spectre,Daniel Craig,Sam Mendes,726.7,206.3,30.0
The Living Daylights,Timothy Dalton,John Glen,313.5,68.8,5.2
The Man with the Golden Gun,Roger Moore,Guy Hamilton,334.0,27.7,NaN
The Spy Who Loved Me,Roger Moore,Lewis Gilbert,533.0,45.1,NaN
The World Is Not Enough,Pierce Brosnan,Michael Apted,439.5,158.3,13.5
Thunderball,Sean Connery,Terence Young,848.1,41.9,4.7
Tomorrow Never Dies,Pierce Brosnan,Roger Spottiswoode,463.2,133.9,10.0
You Only Live Twice,Sean Connery,Lewis Gilbert,514.2,59.9,4.4

## Create Random Sample with the sample Method
- The `sample` method returns a specified one or more random rows from the **DataFrame**.
- Customize the axis parameter to extract random columns.

In [14]:
bond = bond_df.copy().set_index("Film").sort_index()
bond.head()

,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
Film,,,,,,
A View to a Kill,1985,Roger Moore,John Glen,275.2,54.5,9.1
Casino Royale,2006,Daniel Craig,Martin Campbell,581.5,145.3,3.3
Casino Royale,1967,David Niven,Ken Hughes,315.0,85.0,NaN
Diamonds Are Forever,1971,Sean Connery,Guy Hamilton,442.5,34.7,5.8
Die Another Day,2002,Pierce Brosnan,Lee Tamahori,465.4,154.2,17.9

In [32]:
pd.concat([bond.sample() for i in range (0,4)])

,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
Film,,,,,,
The Spy Who Loved Me,1977,Roger Moore,Lewis Gilbert,533.0,45.1,NaN
Skyfall,2012,Daniel Craig,Sam Mendes,943.5,170.2,14.5
Quantum of Solace,2008,Daniel Craig,Marc Forster,514.2,181.4,8.1
For Your Eyes Only,1981,Roger Moore,John Glen,449.4,60.2,NaN

In [34]:
bond.sample(n=10, axis="rows")

,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
Film,,,,,,
Casino Royale,1967,David Niven,Ken Hughes,315.0,85.0,NaN
A View to a Kill,1985,Roger Moore,John Glen,275.2,54.5,9.1
Thunderball,1965,Sean Connery,Terence Young,848.1,41.9,4.7
Never Say Never Again,1983,Sean Connery,Irvin Kershner,380.0,86.0,NaN
The Living Daylights,1987,Timothy Dalton,John Glen,313.5,68.8,5.2
The World Is Not Enough,1999,Pierce Brosnan,Michael Apted,439.5,158.3,13.5
Diamonds Are Forever,1971,Sean Connery,Guy Hamilton,442.5,34.7,5.8
Spectre,2015,Daniel Craig,Sam Mendes,726.7,206.3,30.0
Dr. No,1962,Sean Connery,Terence Young,448.8,7.0,0.6
On Her Majesty's Secret Service,1969,George Lazenby,Peter R. Hunt,291.5,37.3,0.6

In [35]:
bond.sample(n=2, axis="columns") # Keep 2 random columns... ya I don't know why you would want to do this either

                                 Year           Actor
Film
A View to a Kill                 1985     Roger Moore
Casino Royale                    2006    Daniel Craig
Casino Royale                    1967     David Niven
Diamonds Are Forever             1971    Sean Connery
Die Another Day                  2002  Pierce Brosnan
Dr. No                           1962    Sean Connery
For Your Eyes Only               1981     Roger Moore
From Russia with Love            1963    Sean Connery
GoldenEye                        1995  Pierce Brosnan
Goldfinger                       1964    Sean Connery
Licence to Kill                  1989  Timothy Dalton
Live and Let Die                 1973     Roger Moore
Moonraker                        1979     Roger Moore
Never Say Never Again            1983    Sean Connery
No Time to Die                   2021    Daniel Craig
Octopussy                        1983     Roger Moore
On Her Majesty's Secret Service  1969  George Lazenby
Quantum of Solace                2008    Daniel Craig
Skyfall                          2012    Daniel Craig
Spectre                          2015    Daniel Craig
The Living Daylights             1987  Timothy Dalton
The Man with the Golden Gun      1974     Roger Moore
The Spy Who Loved Me             1977     Roger Moore
The World Is Not Enough          1999  Pierce Brosnan
Thunderball                      1965    Sean Connery
Tomorrow Never Dies              1997  Pierce Brosnan
You Only Live Twice              1967    Sean Connery

## The nsmallest and nlargest Methods
- The `nlargest` method returns a specified number of rows with the largest values from a given column
- The `nsmallest` method returns rows with the smallest values from a given column.
- the `nlargest` and `nsmallest` methods are more efficient than sorting the entire `DataFrame`.

In [36]:
bond = bond_df.copy().set_index("Film").sort_index()
bond.head()

,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
Film,,,,,,
A View to a Kill,1985,Roger Moore,John Glen,275.2,54.5,9.1
Casino Royale,2006,Daniel Craig,Martin Campbell,581.5,145.3,3.3
Casino Royale,1967,David Niven,Ken Hughes,315.0,85.0,NaN
Diamonds Are Forever,1971,Sean Connery,Guy Hamilton,442.5,34.7,5.8
Die Another Day,2002,Pierce Brosnan,Lee Tamahori,465.4,154.2,17.9

In [40]:
bond.nsmallest(3, columns=["Year", "Box Office"])

,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
Film,,,,,,
Dr. No,1962,Sean Connery,Terence Young,448.8,7.0,0.6
From Russia with Love,1963,Sean Connery,Terence Young,543.8,12.6,1.6
Goldfinger,1964,Sean Connery,Guy Hamilton,820.4,18.6,3.2

In [41]:
bond.nlargest(4, columns=["Box Office"])

,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
Film,,,,,,
Skyfall,2012,Daniel Craig,Sam Mendes,943.5,170.2,14.5
Thunderball,1965,Sean Connery,Terence Young,848.1,41.9,4.7
Goldfinger,1964,Sean Connery,Guy Hamilton,820.4,18.6,3.2
No Time to Die,2021,Daniel Craig,Cary Joji Fukunaga,774.2,301.0,25.0

In [42]:
bond["Box Office"].nlargest(4)

Film
Skyfall           943.5
Thunderball       848.1
Goldfinger        820.4
No Time to Die    774.2
Name: Box Office, dtype: float64

## Filtering with the where Method
- Similar to square brackets or `loc`, the `where` method filters the original `DataFrame` with a Boolean Series.
- All rows present but rows that have `False` in the boolean series will have `NaN` populate for every cell value

In [43]:
bond = bond_df.copy().set_index("Film").sort_index()
bond.head()

,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
Film,,,,,,
A View to a Kill,1985,Roger Moore,John Glen,275.2,54.5,9.1
Casino Royale,2006,Daniel Craig,Martin Campbell,581.5,145.3,3.3
Casino Royale,1967,David Niven,Ken Hughes,315.0,85.0,NaN
Diamonds Are Forever,1971,Sean Connery,Guy Hamilton,442.5,34.7,5.8
Die Another Day,2002,Pierce Brosnan,Lee Tamahori,465.4,154.2,17.9

In [44]:
bond.where(bond["Actor"] == "Sean Connery")

,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
Film,,,,,,
A View to a Kill,NaN,NaN,NaN,NaN,NaN,NaN
Casino Royale,NaN,NaN,NaN,NaN,NaN,NaN
Casino Royale,NaN,NaN,NaN,NaN,NaN,NaN
Diamonds Are Forever,1971.0,Sean Connery,Guy Hamilton,442.5,34.7,5.8
Die Another Day,NaN,NaN,NaN,NaN,NaN,NaN
Dr. No,1962.0,Sean Connery,Terence Young,448.8,7.0,0.6
For Your Eyes Only,NaN,NaN,NaN,NaN,NaN,NaN
From Russia with Love,1963.0,Sean Connery,Terence Young,543.8,12.6,1.6
GoldenEye,NaN,NaN,NaN,NaN,NaN,NaN
Goldfinger,1964.0,Sean Connery,Guy Hamilton,820.4,18.6,3.2
Licence to Kill,NaN,NaN,NaN,NaN,NaN,NaN
Live and Let Die,NaN,NaN,NaN,NaN,NaN,NaN
Moonraker,NaN,NaN,NaN,NaN,NaN,NaN
Never Say Never Again,1983.0,Sean Connery,Irvin Kershner,380.0,86.0,NaN
No Time to Die,NaN,NaN,NaN,NaN,NaN,NaN
Octopussy,NaN,NaN,NaN,NaN,NaN,NaN
On Her Majesty's Secret Service,NaN,NaN,NaN,NaN,NaN,NaN
Quantum of Solace,NaN,NaN,NaN,NaN,NaN,NaN
Skyfall,NaN,NaN,NaN,NaN,NaN,NaN
Spectre,NaN,NaN,NaN,NaN,NaN,NaN
The Living Daylights,NaN,NaN,NaN,NaN,NaN,NaN
The Man with the Golden Gun,NaN,NaN,NaN,NaN,NaN,NaN
The Spy Who Loved Me,NaN,NaN,NaN,NaN,NaN,NaN
The World Is Not Enough,NaN,NaN,NaN,NaN,NaN,NaN
Thunderball,1965.0,Sean Connery,Terence Young,848.1,41.9,4.7
Tomorrow Never Dies,NaN,NaN,NaN,NaN,NaN,NaN
You Only Live Twice,1967.0,Sean Connery,Lewis Gilbert,514.2,59.9,4.4

## The apply Method w/ DF

In [61]:
bond = bond_df.copy().set_index("Film").sort_index()
bond.head()

,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
Film,,,,,,
A View to a Kill,1985,Roger Moore,John Glen,275.2,54.5,9.1
Casino Royale,2006,Daniel Craig,Martin Campbell,581.5,145.3,3.3
Casino Royale,1967,David Niven,Ken Hughes,315.0,85.0,NaN
Diamonds Are Forever,1971,Sean Connery,Guy Hamilton,442.5,34.7,5.8
Die Another Day,2002,Pierce Brosnan,Lee Tamahori,465.4,154.2,17.9

In [60]:
bond.apply(lambda row: print(row.loc["Year"]), axis="columns")

1985
2006
1967
1971
2002
1962
1981
1963
1995
1964
1989
1973
1979
1983
2021
1983
1969
2008
2012
2015
1987
1974
1977
1999
1965
1997
1967

Film
A View to a Kill                   None
Casino Royale                      None
Casino Royale                      None
Diamonds Are Forever               None
Die Another Day                    None
Dr. No                             None
For Your Eyes Only                 None
From Russia with Love              None
GoldenEye                          None
Goldfinger                         None
Licence to Kill                    None
Live and Let Die                   None
Moonraker                          None
Never Say Never Again              None
No Time to Die                     None
Octopussy                          None
On Her Majesty's Secret Service    None
Quantum of Solace                  None
Skyfall                            None
Spectre                            None
The Living Daylights               None
The Man with the Golden Gun        None
The Spy Who Loved Me               None
The World Is Not Enough            None
Thunderball                        None
Tomorrow Never Dies                None
You Only Live Twice                None
dtype: object

In [72]:
def double_budget(row):
    new_row = row.copy()
    new_row.loc["Budget"] = new_row.loc["Budget"]  * 2
    return new_row

In [73]:
bond.apply(double_budget, axis="columns")

,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
Film,,,,,,
A View to a Kill,1985,Roger Moore,John Glen,275.2,109.0,9.1
Casino Royale,2006,Daniel Craig,Martin Campbell,581.5,290.6,3.3
Casino Royale,1967,David Niven,Ken Hughes,315.0,170.0,NaN
Diamonds Are Forever,1971,Sean Connery,Guy Hamilton,442.5,69.4,5.8
Die Another Day,2002,Pierce Brosnan,Lee Tamahori,465.4,308.4,17.9
Dr. No,1962,Sean Connery,Terence Young,448.8,14.0,0.6
For Your Eyes Only,1981,Roger Moore,John Glen,449.4,120.4,NaN
From Russia with Love,1963,Sean Connery,Terence Young,543.8,25.2,1.6
GoldenEye,1995,Pierce Brosnan,Martin Campbell,518.5,153.8,5.1
Goldfinger,1964,Sean Connery,Guy Hamilton,820.4,37.2,3.2
Licence to Kill,1989,Timothy Dalton,John Glen,250.9,113.4,7.9
Live and Let Die,1973,Roger Moore,Guy Hamilton,460.3,61.6,NaN
Moonraker,1979,Roger Moore,Lewis Gilbert,535.0,183.0,NaN
Never Say Never Again,1983,Sean Connery,Irvin Kershner,380.0,172.0,NaN
No Time to Die,2021,Daniel Craig,Cary Joji Fukunaga,774.2,602.0,25.0
Octopussy,1983,Roger Moore,John Glen,373.8,107.8,7.8
On Her Majesty's Secret Service,1969,George Lazenby,Peter R. Hunt,291.5,74.6,0.6
Quantum of Solace,2008,Daniel Craig,Marc Forster,514.2,362.8,8.1
Skyfall,2012,Daniel Craig,Sam Mendes,943.5,340.4,14.5
Spectre,2015,Daniel Craig,Sam Mendes,726.7,412.6,30.0
The Living Daylights,1987,Timothy Dalton,John Glen,313.5,137.6,5.2
The Man with the Golden Gun,1974,Roger Moore,Guy Hamilton,334.0,55.4,NaN
The Spy Who Loved Me,1977,Roger Moore,Lewis Gilbert,533.0,90.2,NaN
The World Is Not Enough,1999,Pierce Brosnan,Michael Apted,439.5,316.6,13.5
Thunderball,1965,Sean Connery,Terence Young,848.1,83.8,4.7
Tomorrow Never Dies,1997,Pierce Brosnan,Roger Spottiswoode,463.2,267.8,10.0
You Only Live Twice,1967,Sean Connery,Lewis Gilbert,514.2,119.8,4.4